overrides:

  - files: "*.js"
    options:
      printWidth: 100
      tabWidth: 4
      semi: false
      singleQuote: true
      trailingComma: "es5"

  - files: "*.md"
    options:
      printWidth: 80
      proseWrap: "always"
