[workspace]

members = [
    "build-utilities",
    "lib/prelude",
    "lib/core",
    "lib/core/fonts-base",
    "lib/core/msdf-sys",
    "lib/backend/webgl",
    "lib/system/web",
]

[profile.release]
opt-level = 3
