[package]
name = "file-manager-server"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[dependencies]
failure     = "0.1.6"
futures     = "0.3.1"
paste       = "0.1.6"
serde_json  = "1.0"
tungstenite = "0.10.1"

chrono     = { version = "0.4"    , features = ["serde"] }
serde      = { version = "1.0"    , features = ["derive"] }
uuid       = { version = "0.8"    , features = ["serde", "v5"] }

file-manager-client = { version = "0.1.0"  , path = ".." }
json-rpc            = { version = "0.1.0"  , path = "../../json-rpc" }
enso-prelude        = { version = "0.1.0"  , path = "../../../lib/prelude" }
utils               = { version = "0.1.0"  , path = "../../utils" }
