[package]
name    = "ast"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more  = { version = "0.15.0"                                           }
failure      = { version = "0.1.5"                                            }
lazy_static =  { version = "1.4.0"                                            }
regex        = { version = "1"                                                }
serde        = { version = "1.0", features = ["derive", "rc"]                 }
serde_json   = { version = "1.0"                                              }
shrinkwraprs = { version = "0.2.1"                                            }
uuid         = { version  = "0.8.1", features = ["serde","v4","wasm-bindgen"] }

ast-macros   = { version = "0.1.0", path = "../macros"                      }
data         = { version = "0.1.0", path = "../../../lib/data"              }
enso-prelude = { version = "0.1.0", path = "../../../lib/enso-prelude"      }
enso-shapely = { version = "0.1.0", path = "../../../lib/enso-shapely/impl" }
utils        = { version = "0.1.0", path = "../../utils"                    }
