[package]
name    = "ide-view-graph-editor"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ast                  = { version = "0.1.0", path = "../../lib/ast/impl"                }
enso-frp             = { version = "0.1.0", path = "../../../lib/frp"                  }
enso-prelude         = { version = "0.1.0", path = "../../../lib/enso-prelude"         }
ensogl               = { version = "0.1.0", path = "../../../ensogl"                   }
ensogl-gui-list-view = { version = "0.1.0", path = "../../../ensogl/lib/list-view"     }
ensogl-text          = { version = "0.1.0", path = "../../../ensogl/lib/text"          }
ensogl-text-msdf-sys = { version = "0.1.0", path = "../../../ensogl/lib/text/msdf-sys" }
ensogl-theme         = { version = "0.1.0", path = "../../../ensogl/lib/theme"         }
enso-shapely         = { version = "0.1.0", path = "../../../lib/enso-shapely/impl"    }
span-tree            = { version = "0.1.0", path = "../../lib/span-tree"               }
logger               = { version = "0.1.0", path = "../../../lib/logger"               }
enso-protocol        = { version = "0.1.0", path = "../../lib/enso-protocol"           }

js-sys       = { version = "0.3.28"                                             }
nalgebra     = { version = "0.21.1"  , features = ["serde-serialize"]           }
serde_json   = { version = "1.0"                                                }
serde        = { version = "1.0"     , features = ["derive"]                    }
uuid         = { version = "0.8"     , features = ["serde","v4","wasm-bindgen"] }
wasm-bindgen = { version = "=0.2.58" , features = ["nightly","serde-serialize"] }

[dependencies.web-sys]
version = "0.3.4"
features = []
