[workspace]

members = [
    "build",
    "ensogl",
    "ensogl/embedded-fonts",
    "ensogl/msdf-sys",
    "ensogl/lib/text",
    "ide",
    "ide/ast/impl",
    "ide/ast/macros",
    "ide/enso-protocol",
    "ide/json-rpc",
    "ide/parser",
    "ide/span-tree",
    "ide/utils",

    "lib/callback",
    "lib/code-builder",
    "lib/data",
    "lib/debug-scenes",
    "lib/enso-macro-utils",
    "lib/enso-prelude",
    "lib/enso-shapely/impl",
    "lib/enso-shapely/macros",
    "lib/eval-tt",
    "lib/frp",
    "lib/generics",
    "lib/graph-editor",
    "lib/logger",
    "lib/optics",
    "lib/system/web",
    "lib/types",
]

[profile.dev]
opt-level = 0
lto       = false
debug     = true

[profile.release]
opt-level = 3
lto       = true
debug     = false

[profile.bench]
opt-level = 3
lto       = true
debug     = false

[profile.test]
opt-level = 0
lto       = false
debug     = true
