[package]
name = "ensogl-core-embedded-fonts"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enso-prelude           = { version = "0.1.0", path="../../../lib/enso-prelude" }

[build-dependencies]
ensogl-build-utilities = { version = "0.1.0", path="../../../build" }
zip                    = { version = "0.5"                          }
