[package]
name    = "ensogl"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = ["statistics", "no_unboxed_callbacks"]
statistics = []
no_unboxed_callbacks = []

[dependencies]
enso-callback              = { version = "0.1.0"  , path = "../lib/callback"      }
ensogl-core-embedded-fonts = { version = "0.1.0"  , path = "embedded-fonts"      }
ensogl-core-msdf-sys       = { version = "0.1.0"  , path = "msdf-sys"            }
enso-prelude               = { version = "0.1.0"  , path = "../lib/prelude"      }
ensogl-system-web          = { version = "0.1.0"  , path = "../lib/system/web"   }
code-builder               = { version = "0.1.0"  , path = "../lib/code-builder" }
data                       = { version = "0.1.0"  , path = "../lib/data"         }
enso-frp                   = { version = "0.1.0"  , path = "../lib/frp"          }
eval-tt                    = { version = "0.1.0"  , path = "../lib/eval-tt"      }
logger                     = { version = "0.1.0"  , path = "../lib/logger"       }
optics                     = { version = "0.1.0"  , path = "../lib/optics"       }
shapely                    = { version = "0.1.0"  , path = "../lib/shapely/impl" }

bit_field                  = { version = "0.10.0"                                }
console_error_panic_hook   = { version = "0.1.6"                                 }
enum_dispatch              = { version = "0.2.0"                                 }
failure                    = { version = "0.1.5"                                 }
Inflector                  = { version = "0.11.4"                                }
itertools                  = { version = "0.8"                                   }
js-sys                     = { version = "0.3.28"                                }
nalgebra                   = { version = "0.19.0"                                }
num_enum                   = { version = "0.4.2"                                 }
num-traits                 = { version = "0.2"                                   }
paste                      = { version = "0.1.6"                                 }
palette                    = { version = "0.5.0"                                 }
rustc-hash                 = { version = "1.0.1"                                 }
shrinkwraprs               = { version = "0.3.0"                                 }
smallvec                   = { version = "1.0.0"                                 }
typenum                    = { version = "1.11.2"                                }
# We require exact version of wasm-bindgen because we do patching final js in our build process,
# and this is vulnerable to any wasm-bindgen version change.
wasm-bindgen               = { version = "=0.2.58" , features = ["nightly"]      }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'CanvasRenderingContext2d',
  'CssStyleDeclaration',
  'Document',
  'Element',
  'EventTarget',
  'KeyboardEvent',
  'HtmlCanvasElement',
  'HtmlCollection',
  'HtmlDivElement',
  'HtmlElement',
  'HtmlImageElement',
  'Location',
  'Node',
  'Url',
  'WebGlBuffer',
  'WebGlFramebuffer',
  'WebGlProgram',
  'WebGlRenderingContext',
  'WebGlShader',
  'WebGlSync',
  'WebGlTexture',
  'WebGlUniformLocation',
  'WebGlUniformLocation',
  'WebGlVertexArrayObject',
  'Window',
  'console',
  'EventTarget',
  'Event',
  'MouseEvent',
  'WheelEvent',
  'DomRect',
  'AddEventListenerOptions'
]

[dev-dependencies]
assert_approx_eq  = { version = "1.1.0"                           }
wasm-bindgen-test = { version = "0.3.8"                           }
web-test          = { version = "0.1.0", path = "../lib/web-test" }
