[package]
name    = "ensogl"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[features]

[dependencies]
ensogl-core = { path = "lib/core" }
ensogl-text = { path = "lib/text" }
