[package]
name    = "enso-protocol"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
data         = { version = "0.1.0"  , path = "../../lib/data"   }
json-rpc     = { version = "0.1.0"  , path = "../json-rpc"      }
enso-prelude = { version = "0.1.0"                              }
enso-shapely = { version = "0.1.0"                              }
logger       = { version = "0.1.0"  , path = "../../lib/logger" }
utils        = { version = "0.1.0"  , path = "../utils"         }

chrono      = { version = "0.4"  , features = ["serde"]                       }
failure     = { version = "0.1.8"                                             }
flatbuffers = { version = "0.5"                                               }
futures     = { version = "0.3.1"                                             }
mockall     = { version = "0.7.1", features = ["nightly"]                     }
hex         = { version = "0.4.2"                                             }
serde       = { version = "1.0"  , features = ["derive"]                      }
serde_json  = { version = "1.0"                                               }
sha3        = { version = "0.8.2"                                             }
uuid        = { version = "0.8"  , features = ["serde", "v4", "wasm-bindgen"] }


[dev-dependencies]
wasm-bindgen-test = { version = "0.3.8"                                     }
ensogl-system-web = { version = "0.1.0"  , path = "../../lib/system/web"    }


[build-dependencies]
ensogl-build-utilities = { version = "0.1.0"  , path = "../../build"  }
bytes                  = { version = "0.5.4"                          }
flatc-rust             = { version = "0.1.2"                          }
futures                = { version = "0.3.1"                          }
reqwest                = { version = "0.10.1"                         }
tokio                  = { version = "0.2.10" , features = ["macros"] }
# Zip is needed because the build script downloads and extracts artifacts from the Engine.
zip                    = { version = "0.5.0"                          }
zip-extensions         = { version = "0.4.0"                          }
