[package]
name = "json-rpc"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
enso-prelude      = { version = "0.1.0" , path = "../../lib/prelude"      }
ensogl-system-web = { version = "0.1.0" , path = "../../lib/system/web"   }

futures           = { version = "0.3.1"                                   }
failure           = { version = "0.1.6"                                   }
serde             = { version = "1.0.0" , features = ["derive"]           }
serde_json        = { version = "1.0.0"                                   }
shapely           = { version = "0.1.0" , path = "../../lib/shapely/impl" }
shrinkwraprs      = { version = "0.3.0"                                   }
utils             = { version = "0.1.0" , path = "../utils"               }
