blank_issues_enabled: false
contact_links:
  - name: Issues with Enso?
    url: https://github.com/enso-org/enso/issues/new/choose
    about: Please report problems with the Enso in the Enso repository.
  - name: Have a question about Enso?
    url: https://github.com/enso-org/enso/discussions/new?category=Questions
    about: Ask your questions about Enso
  - name: Want to discuss Enso?
    url: https://github.com/enso-org/enso/discussions/new?category=general
    about: Talk about Enso the language
  - name: Have an idea?
    url: https://github.com/enso-org/enso/discussions/new?category=ideas
    about: Share your ideas for Enso
