[package]
name    = "ensogl-core-msdf-sys"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen   = { version = "=0.2.58"                                 }
js-sys         = { version = "0.3.30"                                  }
nalgebra       = { version = "0.21.1"                                  }
enso-prelude   = { version = "0.1.0", path="../../../lib/enso-prelude" }

[dev-dependencies]
wasm-bindgen-test          = { version = "0.3.8"                           }
futures                    = { version = "0.3.1"                           }
ensogl-core-embedded-fonts = { version = "0.1.0", path="../embedded-fonts" }

[build-dependencies]
ensogl-build-utilities = { version = "0.1.0", path="../../../build" }
