// THIS IS AN AUTOGENERATED FILE BASED ON THE '../../../config.yaml' CONFIG FILE. DO NOT MODIFY IT.

#![allow(non_upper_case_globals)]

pub struct Config {
    pub window_app_scope_name : &'static str,
    pub window_app_scope_config_name : &'static str,
    pub window_app_scope_theme_name : &'static str,
}

pub const CONFIG : Config = Config {
    window_app_scope_name : "enso",
    window_app_scope_config_name : "config",
    window_app_scope_theme_name : "theme",
};

pub const window_app_scope_name : &str = "enso";
pub const window_app_scope_config_name : &str = "config";
pub const window_app_scope_theme_name : &str = "theme";
