[package]
name    = "parser"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"
build   = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ast          = { version = "0.1.0", path = "../ast/impl" }
data         = { version = "0.1.0", path = "../../lib/data" }
enso-prelude = { version = "0.1.0", path = "../../lib/prelude" }
utils        = { version = "0.1.0", path = "../utils" }

console_error_panic_hook = { version = "0.1.6" }
failure                  = { version = "0.1" }
js-sys                   = { version = "0.3" }
matches                  = { version = "0.1" }
serde                    = { version = "1.0" , features = ["derive"] }
serde_json               = { version = "1.0" }
shrinkwraprs             = { version = "0.2.1" }
uuid                     = { version = "0.8" , features = ["serde", "v5", "wasm-bindgen"] }
wasm-bindgen             = { version = "=0.2.58" }

[dev-dependencies]
wasm-bindgen-test        = { version = "0.3.8" }

[build-dependencies]
ensogl-build-utilities = { version = "0.1.0", path = "../../build" }
bytes                  = { version = "0.5.4" }
futures                = { version = "0.3.1" }
reqwest                = { version = "0.10.1" }
tokio                  = { version = "0.2.10", features = ["macros"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
websocket = "0.23.0"
