[package]
name    = "engine-api"
version = "0.1.0"
authors = ["Enso Team <contact@luna-lang.org>"]
edition = "2018"
build   = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
flatbuffers = "0.5"

[build-dependencies]
ensogl-build-utilities = { version = "0.1.0"  , path = "../../build"  }
bytes                  = { version = "0.5.4"                          }
flatc-rust             = { version = "0.1.2"                          }
futures                = { version = "0.3.1"                          }
reqwest                = { version = "0.10.1"                         }
tokio                  = { version = "0.2.10" , features = ["macros"] }
zip                    = { version = "0.5.0"                          }
zip-extensions         = { version = "0.4.0"                          }
