# The name of an object created in the global window scope. This object will contain functions
# to control the IDE, like the `main` function, and also the configuration object.
windowAppScopeName: "enso"

# The configuration object nested inside of the `windowAppScopeName` object containing all
# startup configuration options. See usages of this variable to learn more about available
# options.
windowAppScopeConfigName: "config"

# The configuration object nested inside of the `windowAppScopeName` object containing theming
# utilities and allowing for runtime theme modification.
windowAppScopeThemeName: "theme"
