name: Build (MacOS, Linux, Windows)

on: [push]

# Please check if all components are available before updating the rust toolchain version.
# https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html

jobs:
  build:
    name: Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn
        working-directory: ./app
      - run: npm install
        working-directory: ./app
      - run: npm run dist
        working-directory: ./app
      - run: ls -R app/dist 

      - uses: actions/upload-artifact@v1
        name: Upload Artifacts (Windows)
        with:
          name: Enso IDE (Linux, AppImage)
          path: app/dist/enso-ide-0.1.0.AppImage
        if: matrix.os == 'ubuntu-latest'

      - uses: actions/upload-artifact@v1
        name: Upload Artifacts (Windows)
        with:
          name: Enso IDE (Linux, unpacked)
          path: app/dist/linux-unpacked
        if: matrix.os == 'ubuntu-latest'


      - uses: actions/upload-artifact@v1
        name: Upload Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        with:
          name: Enso IDE (Windows, installer)
          path: app/dist/enso-ide Setup 0.1.0.exe

      - uses: actions/upload-artifact@v1
        name: Upload Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        with:
          name: Enso IDE (Windows, portable)
          path: app/dist/win-unpacked

      - uses: actions/upload-artifact@v1
        name: Upload Artifacts (macOS)
        if: matrix.os == 'macos-latest'
        with:
          name: Enso IDE (macOS, dmg)
          path: app/dist/enso-ide-0.1.0.dmg

      - uses: actions/upload-artifact@v1
        name: Upload Artifacts (macOS)
        if: matrix.os == 'macos-latest'
        with:
          name: Enso IDE (macOS, app)
          path: app/dist/mac/enso-ide.app

