name: Build (MacOS, Linux, Windows)

on: [push]

# Please check if all components are available before updating the rust toolchain version.
# https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn
        working-directory: ./app
      - run: npm install
        working-directory: ./app
      - run: npm run dist
        working-directory: ./app
      - run: ls -R app/dist 
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: my-artifact
      #     path: app/dist/enso-ide Setup 0.1.0.exe

