name: Release
'on':
  push:
    tags:
      - v*
jobs:
  create_release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Enso ${{ github.ref }}
          body_path: CURRENT_RELEASE_CHANGELOG.md
          draft: false
          prerelease: false
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Upload Release (macos, dmg)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: OUT_macos.txt
          asset_name: OUT_macos.txt
          asset_content_type: application/zip
        if: matrix.os == 'macos-latest'
      - name: Upload Release (windows, exe)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: OUT_windows.txt
          asset_name: OUT_windows.txt
          asset_content_type: application/zip
        if: matrix.os == 'windows-latest'
      - name: Upload Release (linux, AppImage)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: OUT_linux.txt
          asset_name: OUT_linux.txt
          asset_content_type: application/zip
        if: matrix.os == 'ubuntu-latest'
