name: GUI CI
'on':
  - push
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Upload Artifacts (macos, dmg)
        uses: actions/upload-artifact@v1
        with:
          name: OUT_macos
          path: OUT_macos.txt
        if: matrix.os == 'macos-latest'
      - name: Upload Artifacts (windows, exe)
        uses: actions/upload-artifact@v1
        with:
          name: OUT_windows
          path: OUT_windows.txt
        if: matrix.os == 'windows-latest'
      - name: Upload Artifacts (linux, AppImage)
        uses: actions/upload-artifact@v1
        with:
          name: OUT_linux
          path: OUT_linux.txt
        if: matrix.os == 'ubuntu-latest'
  upload_to_github:
    name: GitHub Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: ls artifacts
        run: ls -la artifacts
      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: artifacts/**/*
          body_path: CURRENT_RELEASE_CHANGELOG.md
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
  upload_to_cdn:
    name: CDN Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
